import typeIMG from "../assets/type.png";

export default [
  { id: 1, nome: "Podcasts", imagem: typeIMG, cor: "#E13300" },
  { id: 2, nome: "Feito para\nvocê", imagem: typeIMG, cor: "#1E3264" },
  { id: 3, nome: "Lançamentos", imagem: typeIMG, cor: "#E8125C" },
  { id: 4, nome: "Brasil", imagem: typeIMG, cor: "#C0964C" },
  { id: 5, nome: "Sertanejo", imagem: typeIMG, cor: "#537AA1" },
  { id: 6, nome: "Funk", imagem: typeIMG, cor: "#E51E31" },
  { id: 7, nome: "Pop", imagem: typeIMG, cor: "#158A08" },
  { id: 8, nome: "Paradas", imagem: typeIMG, cor: "#8C67AC" },
  { id: 9, nome: "Eventos ao\nvivo", imagem: typeIMG, cor: "#7358FF" },
  { id: 10, nome: "Hip Hop", imagem: typeIMG, cor: "#BC5800" },
  { id: 11, nome: "Samba e\npagode", imagem: typeIMG, cor: "#016450" },
  { id: 12, nome: "MPB", imagem: typeIMG, cor: "#84A0AC" },
  { id: 13, nome: "AMPLIFIKA", imagem: typeIMG, cor: "#E9142A" },
  { id: 14, nome: "Descobrir", imagem: typeIMG, cor: "#8C67AC" },
  { id: 15, nome: "Rádio", imagem: typeIMG, cor: "#B02896" },
  { id: 16, nome: "Dance/\nEletronica", imagem: typeIMG, cor: "#D84000" },
  { id: 17, nome: "Música Cristã", imagem: typeIMG, cor: "#0F5FC0" },
  { id: 18, nome: "Rock", imagem: typeIMG, cor: "#AB1320" },
  { id: 19, nome: "Jazz", imagem: typeIMG, cor: "#FEC800" },
  { id: 20, nome: "Classica", imagem: typeIMG, cor: "#3C3C3C" },
  { id: 21, nome: "Independente", imagem: typeIMG, cor: "#CCB9A8" },
  { id: 22, nome: "Metal", imagem: typeIMG, cor: "#707070" },
  { id: 23, nome: "Reggae", imagem: typeIMG, cor: "#1A802A" },
  { id: 24, nome: "Country", imagem: typeIMG, cor: "#8F6A47" },
  { id: 25, nome: "Blues", imagem: typeIMG, cor: "#004B8D" },
  { id: 26, nome: "Alternativa", imagem: typeIMG, cor: "#6B2E5F" },
  { id: 27, nome: "", imagem: "", cor: "#121212" },
  { id: 27, nome: "", imagem: "", cor: "#121212" },
];
